# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-30 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='corp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbsite.Corp'),
        ),
    ]
