# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-30 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbsite', '0002_auto_20170730_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kill',
            name='victim',
        ),
        migrations.AddField(
            model_name='kill',
            name='victim_agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kbsite.Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kill',
            name='victim_robot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kbsite.Robot'),
            preserve_default=False,
        ),
    ]
