# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-30 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kbsite', '0003_auto_20170730_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackdetails',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbsite.Player'),
        ),
        migrations.AlterField(
            model_name='kill',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbsite.Zone'),
        ),
    ]
